compute_environment: LOCAL_MACHINE
#deepspeed_config:
#  deepspeed_hostfile: hostfile
#  deepspeed_multinode_launcher: pdsh
#  gradient_clipping: 1.0
#  offload_optimizer_device: cpu
#  offload_param_device: cpu
#  zero3_init_flag: true
#  zero3_save_16bit_model: true
#  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'yes'
dynamo_config:
  dynamo_backend: EAGER
machine_rank: 0
main_process_ip: 192.168.11.161
main_process_port: 29999
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
